---
- name: Check if helm is installed
  ignore_errors: true
  command: helm version
  register: helm_install_version

- name: Sync helm to remote
  copy:
    src: "{{ work_dir }}/kubekey/helm/{{ helm_version }}/{{ binary_type.stdout }}/helm-{{ helm_version }}-linux-{{ binary_type.stdout }}.tar.gz"
    dest: "/tmp/kubekey/helm-{{ helm_version }}-linux-{{ binary_type.stdout }}.tar.gz"
  when: helm_install_version.stderr != ""

- name: Install helm
  command: |
    tar --strip-components=1 -zxvf /tmp/kubekey/helm-{{ helm_version }}-linux-{{ binary_type.stdout }}.tar.gz -C /usr/local/bin linux-{{ binary_type.stdout }}/helm
  when: helm_install_version.stderr != ""

- name: Check if kubeadm is installed
  ignore_errors: true
  command: kubeadm version
  register: kubeadm_install_version

- name: Sync kubeadm to remote
  copy:
    src: "{{ work_dir }}/kubekey/kube/{{ kube_version }}/{{ binary_type.stdout }}/kubeadm"
    dest: "/usr/local/bin/kubeadm"
    mode: 0755
  when: kubeadm_install_version.stderr != ""

- name: Check if kubectl is installed
  ignore_errors: true
  command: kubectl version
  register: kubectl_install_version

- name: Sync kubectl to remote
  copy:
    src: "{{ work_dir }}/kubekey/kube/{{ kube_version }}/{{ binary_type.stdout }}/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: 0755
  when: kubectl_install_version.stderr != ""


- name: Check if kubelet is installed
  ignore_errors: true
  command: systemctl status kubelet
  register: kubelet_install_version

- name: Sync kubelet to remote
  copy:
    src: "{{ work_dir }}/kubekey/kube/{{ kube_version }}/{{ binary_type.stdout }}/kubelet"
    dest: "/usr/local/bin/kubelet"
    mode: 0755
  when: kubelet_install_version.stderr != ""

- name: Sync kubelet env to remote
  template:
    src: "kubeadm/kubelet.env"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"
  when: kubelet_install_version.stderr != ""

- name: Sync kubelet service to remote
  copy:
    src: "kubelet.service"
    dest: "/etc/systemd/system/kubelet.service"
  when: kubelet_install_version.stderr != ""

- name: Register kubelet service
  command: systemctl daemon-reload && systemctl enable kubelet.service
  when: kubelet_install_version.stderr != ""
