---
- include_tasks: kube.yaml
  tags: ["certs"]

- include_tasks: etcd.yaml
  tags: ["certs"]
  when:
  - kubernetes.etcd.deployment_type=='external' && groups['etcd']|length > 0
  - renew_etcd

- name: Reload kubernetes pods
  tags: [ "certs" ]
  command: |
    {% if (cri.container_manager == "docker") %}
    docker ps -af name=k8s_PODS_kube-apiserver* -q | xargs --no-run-if-empty docker rm -f
    docker ps -af name=k8s_PODS_kube-controller-manager* -q | xargs --no-run-if-empty docker rm -f
    docker ps -af name=k8s_PODS_kube-scheduler* -q | xargs --no-run-if-empty docker rm -f
    {% if (kubernetes.etcd.deployment_type=='internal' && renew_etcd ) %}
    docker ps -af name=k8s_PODS_etcd* -q | xargs --no-run-if-empty docker rm -f
    {% endif %}
    {% else %}
    crictl pods --name kube-apiserver-* -q | xargs -I% --no-run-if-empty bash -c 'crictl stopp % && crictl rmp %'
    crictl pods --name kube-controller-manager-* -q | xargs -I% --no-run-if-empty bash -c 'crictl stopp % && crictl rmp %'
    crictl pods --name kube-scheduler-* -q | xargs -I% --no-run-if-empty bash -c 'crictl stopp % && crictl rmp %'
    {% if (kubernetes.etcd.deployment_type=='internal' && renew_etcd ) %}
    crictl pods --name etcd-* -q | xargs -I% --no-run-if-empty bash -c 'crictl stopp % && crictl rmp %'
    {% endif %}
    {% endif %}
