---
- name: Stop if unknown network plugin
  assert:
    that: kubernetes.kube_network_plugin in cluster_require.require_network_plugin
    fail_msg: "{{ kubernetes.kube_network_plugin }} is not supported"
  when:
    - kubernetes.kube_network_plugin | defined

# This assertion will fail on the safe side: One can indeed schedule more pods
# on a node than the CIDR-range has space for when additional pods use the host
# network namespace. It is impossible to ascertain the number of such pods at
# provisioning time, so to establish a guarantee, we factor these out.
# NOTICE: the check blatantly ignores the inet6-case
- name: Guarantee that enough network address space is available for all pods
  assert:
    that: "(kubernetes.kubelet.max_pods | integer)  <= (2 | pow:{{ 32 - kubernetes.controller_manager.kube_network_node_prefix | integer }} - 2)"
    fail_msg: "Do not schedule more pods on a node than inet addresses are available."
  when:
    - inventory_name in groups['k8s_cluster']
    - kubernetes.controller_manager.kube_network_node_prefix | defined
    - kubernetes.kube_network_plugin != 'calico'

