---
- name: Stop if bad hostname
  vars:
    regex: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
  assert:
    that: inventory_name | match:regex
    fail_msg: "Hostname must consist of lower case alphanumeric characters, '.' or '-', and must start and end with an alphanumeric character"

- name: Stop if the os does not support
  assert:
    that: (cluster_require.allow_unsupported_distribution_setup) or (os.release.ID in cluster_require.supported_os_distributions)
    fail_msg: "{{ os.release.ID }} is not a known OS"

- name: Stop if arch supported
  assert:
    that: os.architecture in cluster_require.supported_architectures.amd64 or os.architecture in cluster_require.supported_architectures.arm64
    success_msg: "{% if (os.architecture in cluster_require.supported_architectures.amd64) %}amd64{% else %}arm64{% endif %}"
    fail_msg: "{{ os.architecture }} is not a known OS"
  register: binary_type

- name: Stop if memory is too small for masters
  assert:
    that: process.memInfo.MemTotal | cut:' kB' >= cluster_require.minimal_master_memory_mb
  when:
    - inventory_name in groups['kube_control_plane']

- name: Stop if memory is too small for nodes
  assert:
    that: process.memInfo.MemTotal | cut:' kB' >= cluster_require.minimal_node_memory_mb
  when:
    - inventory_name in groups['kube_worker']

- name: Stop if kernel version is too low
  assert:
    that: os.kernel_version | split:'-' | first | version:'>=4.9.17'
