FROM centos:8 AS centos8
ARG TARGETARCH
ENV OS=centos
ENV OS_VERSION=8
ARG BUILD_TOOLS="dnf-plugins-core createrepo mkisofs epel-release"
ARG DIR=${OS}${OS_VERSION}-${TARGETARCH}-rpms

RUN dnf install -q -y ${BUILD_TOOLS}

WORKDIR package
COPY packages.yaml .
COPY --from=mikefarah/yq:4.11.1 /usr/bin/yq /usr/bin/yq
RUN yq eval ".common[],.rpms[],.${OS}[],.${OS}${OS_VERSION}[]" packages.yaml > packages.list

RUN sort -u packages.list | xargs repotrack -p ${DIR} \
    && createrepo -d ${DIR} \
    && mkisofs -r -o ${DIR}.iso ${DIR}

FROM scratch
COPY --from=centos8 /package/*.iso /
